version: '2.1'

services:
  web:
    image: web
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
  frontend:
    image: image
    build: ./frontend
    environment:
      NODE_ENV: production
    