version: "3.3"

services:
  web:
    image: web
    build: .
    volumes:
      - $PWD:/var/blog

    environment:
      redis: redis
      port: 3001
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    deploy:
          replicas: 4
          restart_policy:
            condition: on-failure
          resources:
            limits:
              cpus: "0.1"
              memory: 50M
    ports:
      - 3001:3001
    
  redis:
    image: redis
    ports:
      - 3797:6379

  postgres:
    image: postgres
    environment:
    volumes:
      - $PWD/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dio
      POSTGRES_USER: dio
      POSTGRES_DB: blog
    ports:
      - 4321:5432