version: '2.1'

services:
  web:
    image: web
    build: .
    environment:
      redis: redis
      port: 3001
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    ports:
      - 3001:3001
    
  redis:
    image: redis
    ports:
      - 3797:6379

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dio
      POSTGRES_USER: dio
      POSTGRES_DB: blog
    ports:
      - 4321:5432