version: '2'

services:
  web:
    image: web
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001

  # frontend:
  #   image: image
  #   build: ./frontend
  #   environment:
  #     NODE_ENV: production
    
  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dio
      POSTGRES_USER: dio
    ports:
      - 5432:5432